// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: osinniychain/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// this line is used by starport scaffolding # 3
type QueryMessagesRequest struct {
	// Adding pagination to request
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryMessagesRequest) Reset()         { *m = QueryMessagesRequest{} }
func (m *QueryMessagesRequest) String() string { return proto.CompactTextString(m) }
func (*QueryMessagesRequest) ProtoMessage()    {}
func (*QueryMessagesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d9af9311ce19ab3, []int{0}
}
func (m *QueryMessagesRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryMessagesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryMessagesRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryMessagesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryMessagesRequest.Merge(m, src)
}
func (m *QueryMessagesRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryMessagesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryMessagesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryMessagesRequest proto.InternalMessageInfo

func (m *QueryMessagesRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryMessagesResponse struct {
	//   string msg = 1;
	// Returning a list of posts
	Msg []*Message `protobuf:"bytes,1,rep,name=Msg,proto3" json:"Msg,omitempty"`
	// Adding pagination to response
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryMessagesResponse) Reset()         { *m = QueryMessagesResponse{} }
func (m *QueryMessagesResponse) String() string { return proto.CompactTextString(m) }
func (*QueryMessagesResponse) ProtoMessage()    {}
func (*QueryMessagesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d9af9311ce19ab3, []int{1}
}
func (m *QueryMessagesResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryMessagesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryMessagesResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryMessagesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryMessagesResponse.Merge(m, src)
}
func (m *QueryMessagesResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryMessagesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryMessagesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryMessagesResponse proto.InternalMessageInfo

func (m *QueryMessagesResponse) GetMsg() []*Message {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (m *QueryMessagesResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryMessagesRequest)(nil), "osinniyapps.osinniychain.osinniychain.QueryMessagesRequest")
	proto.RegisterType((*QueryMessagesResponse)(nil), "osinniyapps.osinniychain.osinniychain.QueryMessagesResponse")
}

func init() { proto.RegisterFile("osinniychain/query.proto", fileDescriptor_5d9af9311ce19ab3) }

var fileDescriptor_5d9af9311ce19ab3 = []byte{
	// 343 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xb1, 0x4a, 0x43, 0x31,
	0x14, 0x86, 0x9b, 0x16, 0x45, 0xd2, 0x2d, 0xa8, 0x94, 0x22, 0x97, 0x52, 0x50, 0x8b, 0x43, 0x42,
	0xeb, 0xa0, 0xa0, 0x83, 0x38, 0xe8, 0x54, 0xd0, 0x3b, 0x3a, 0x08, 0xb9, 0x25, 0xa4, 0x01, 0x9b,
	0xa4, 0x3d, 0xa9, 0xd8, 0xd5, 0x27, 0x10, 0x7c, 0x03, 0x1f, 0xc4, 0xb9, 0x63, 0xc1, 0xc5, 0x51,
	0x5a, 0x1f, 0x44, 0xee, 0xcd, 0x15, 0x6f, 0x44, 0xb1, 0x38, 0x9e, 0xe4, 0xfc, 0xff, 0xff, 0xe5,
	0x9c, 0xe0, 0x9a, 0x01, 0xa5, 0xb5, 0x9a, 0xf4, 0xfa, 0x5c, 0x69, 0x36, 0x1c, 0x8b, 0xd1, 0x84,
	0xda, 0x91, 0x71, 0x86, 0x6c, 0xe7, 0x37, 0xdc, 0x5a, 0xa0, 0xc5, 0xae, 0xa0, 0xa8, 0x6f, 0x49,
	0x63, 0xe4, 0x8d, 0x60, 0xdc, 0x2a, 0xc6, 0xb5, 0x36, 0x8e, 0x3b, 0x65, 0x34, 0x78, 0x93, 0xfa,
	0x5e, 0xcf, 0xc0, 0xc0, 0x00, 0x4b, 0x38, 0x08, 0xef, 0xce, 0x6e, 0xdb, 0x89, 0x70, 0xbc, 0xcd,
	0x2c, 0x97, 0x4a, 0x67, 0xcd, 0x79, 0xef, 0x66, 0x80, 0x32, 0x00, 0xe9, 0xcf, 0x9b, 0xd7, 0x78,
	0xfd, 0x32, 0x55, 0x76, 0x05, 0x00, 0x97, 0x02, 0x62, 0x31, 0x1c, 0x0b, 0x70, 0xe4, 0x0c, 0xe3,
	0x2f, 0x8f, 0x1a, 0x6a, 0xa0, 0x56, 0xb5, 0xb3, 0x43, 0x7d, 0x20, 0x4d, 0x03, 0xa9, 0x7f, 0x4e,
	0x1e, 0x48, 0x2f, 0xb8, 0x14, 0xb9, 0x36, 0x2e, 0x28, 0x9b, 0x4f, 0x08, 0x6f, 0x7c, 0x0b, 0x00,
	0x6b, 0x34, 0x08, 0x72, 0x82, 0x2b, 0x5d, 0x90, 0x35, 0xd4, 0xa8, 0xb4, 0xaa, 0x1d, 0x4a, 0x97,
	0x1a, 0x08, 0xcd, 0x5d, 0xe2, 0x54, 0x4a, 0xce, 0x03, 0xc6, 0x72, 0xc6, 0xb8, 0xfb, 0x27, 0xa3,
	0x8f, 0x2f, 0x42, 0x76, 0xa6, 0x08, 0xaf, 0x64, 0x90, 0xe4, 0x19, 0xe1, 0xb5, 0x4f, 0x52, 0x72,
	0xb4, 0x24, 0xd4, 0x4f, 0x03, 0xac, 0x1f, 0xff, 0x4f, 0xec, 0xe9, 0x9a, 0x07, 0xf7, 0x2f, 0xef,
	0x8f, 0xe5, 0x36, 0x61, 0xac, 0xe0, 0xc2, 0x82, 0x1d, 0x86, 0x0b, 0xcd, 0x0d, 0x4e, 0xe3, 0xe9,
	0x3c, 0x42, 0xb3, 0x79, 0x84, 0xde, 0xe6, 0x11, 0x7a, 0x58, 0x44, 0xa5, 0xd9, 0x22, 0x2a, 0xbd,
	0x2e, 0xa2, 0xd2, 0xd5, 0xa1, 0x54, 0xae, 0x3f, 0x4e, 0x68, 0xcf, 0x0c, 0x7e, 0x37, 0xbd, 0x0b,
	0x4b, 0x37, 0xb1, 0x02, 0x92, 0xd5, 0xec, 0xab, 0xec, 0x7f, 0x04, 0x00, 0x00, 0xff, 0xff, 0xfa,
	0x00, 0x5e, 0xef, 0xcf, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Queries a list of messages items.
	Messages(ctx context.Context, in *QueryMessagesRequest, opts ...grpc.CallOption) (*QueryMessagesResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Messages(ctx context.Context, in *QueryMessagesRequest, opts ...grpc.CallOption) (*QueryMessagesResponse, error) {
	out := new(QueryMessagesResponse)
	err := c.cc.Invoke(ctx, "/osinniyapps.osinniychain.osinniychain.Query/Messages", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Queries a list of messages items.
	Messages(context.Context, *QueryMessagesRequest) (*QueryMessagesResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Messages(ctx context.Context, req *QueryMessagesRequest) (*QueryMessagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Messages not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Messages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Messages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/osinniyapps.osinniychain.osinniychain.Query/Messages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Messages(ctx, req.(*QueryMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "osinniyapps.osinniychain.osinniychain.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Messages",
			Handler:    _Query_Messages_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "osinniychain/query.proto",
}

func (m *QueryMessagesRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryMessagesRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryMessagesRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryMessagesResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryMessagesResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryMessagesResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Msg) > 0 {
		for iNdEx := len(m.Msg) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Msg[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryMessagesRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryMessagesResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Msg) > 0 {
		for _, e := range m.Msg {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryMessagesRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryMessagesRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryMessagesRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryMessagesResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryMessagesResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryMessagesResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Msg", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Msg = append(m.Msg, &Message{})
			if err := m.Msg[len(m.Msg)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
